import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/SessionContext";
import { CartProvider } from "@/context/CartContext";
import { ToastContainer } from "react-toastify";
import { ProductProvider } from "@/context/ProductContext";
import { ResumeProvider } from "@/context/ResumeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sistema de gestión",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ProductProvider>
            <CartProvider>
              <ResumeProvider>
                {children}
              </ResumeProvider>
              <ToastContainer />
            </CartProvider>
          </ProductProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
